channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pybedtools=0.10.0
  - bioconda::pysam=0.22.1
  - bioconda::samtools=1.21
  - conda-forge::biopython=1.83
  - conda-forge::python=3.11.0
  - pip
  - pip:
      - mirtop==0.4.28
      - pandas==2.2.2
