---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - conda-forge::r-base=3.6.2
  - conda-forge::r-data.table=1.12.2
