channels:
  - r
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-limma=3.58.1
  - bioconda::bioconductor-edger=4.0.2
  - conda-forge::r-base=4.3.2
  - conda-forge::r-data.table=1.14.10
  - conda-forge::r-statmod=1.5.0
  - r::r-gplots=3.1.3
